### ISSUE TITLE
一直报这个错

### ISSUE THREAD

**Issue by ZJJHYM** [xx025/chatgptapi_server#11]
INFO:     connection closed
INFO:     ('127.0.0.1', 60066) - "WebSocket /server?token=hkyH8Ldxf17l9N9FYBoa" [accepted]
server449 connected
INFO:     connection open
ERROR:    Exception in ASGI application

**Comment by xx025** [comment]
或许需要一个Redis数据库，redis数据库连接配置见`setting.py`
