### ISSUE TITLE
如何设置多账户

### ISSUE THREAD

**Issue by 050310Y** [xx025/chatgptapi_server#12]
您好，请问如何设置多个账户轮训

**Comment by xx025** [comment]
不同的账户与web服务通过wedsocket协议连接，有一段基于revChatGPT的连接示例代码,见[revChatGPT2](etc/revChatGPT2.py)

**Comment by 050310Y** [comment]
可以有偿修改几个东西吗，qq15001904，麻烦了

**Comment by xx025** [comment]
你这个联系方式加不上

**Comment by 050310Y** [comment]
15001904
